---
title: "git_01"
author: "Saul Perez Ramos"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

'Twas brillig, and the slithy toves    
Did gyre and gimble in the wabe:   
All mimsy were the borogoves,  
And the mome raths outgrabe.  

"Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,    
And sorry I could not travel both    
And be one traveler, long I stood    
And looked down one as far as I could   
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,    
      Shining with all his might:  
He did his very best to make    
      The billows smooth and bright —  
And this was odd, because it was    
      The middle of the night.    
    
The moon was shining sulkily,    
      Because she thought the sun    
Had got no business to be there    
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

If we didn’t have birthdays,    
you wouldn’t be you.    
If you’d never been born,    
well then what would you do?    
If you’d never been born,    
well then what would you be?    
You might be a fish!    
Or a toad in a tree!    
You might be a doorknob!    
Or three baked potatoes!    
You might be a bag full of    
hard green tomatoes.    
    
Or worse than all that…    
Why, you might be a WASN’T!    
A Wasn’t has no fun at all.    
No, he doesn’t.    
  
A Wasn’t just isn’t. He just    
isn’t present. But you…    
You ARE YOU!    
And, now isn’t that pleasant!  